context:
  name: bagels
  version: "0.2.2"
  python_min: "3.13"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 5f6e6bea43c050c8bc8639a6a80621f3609b9986a79b98f90d77793a22284241
  patches:
    - change-xdg-package-name.patch

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0
  python:
    entry_points:
      bagels = bagels.__main__:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - aiohappyeyeballs ==2.4.3
    - aiohttp-jinja2 ==1.6
    - aiohttp ==3.10.10
    - aiosignal ==1.3.1
    - annotated-types ==0.7.0
    - attrs ==24.2.0
    - blinker ==1.8.2
    - click-default-group >=1.2.4
    - click ==8.1.7
    - frozenlist ==1.5.0
    - idna ==3.10
    - itsdangerous ==2.2.0
    - linkify-it-py ==2.0.3
    - markdown-it-py ==3.0.0
    - markupsafe ==3.0.2
    - mdit-py-plugins ==0.4.2
    - mdurl ==0.1.2
    - msgpack-python ==1.1.0
    - multidict ==6.1.0
    - numpy >=2.1.3
    - platformdirs ==4.3.6
    - propcache ==0.2.0
    - pydantic-core ==2.23.4
    - pydantic ==2.9.2
    - pygments ==2.18.0
    - pyyaml ==6.0.2
    - rich ==13.9.3
    - sqlalchemy ==2.0.36
    - textual ==0.86.1
    - tomli >=2.0.2
    - typing-extensions ==4.12.2
    - uc-micro-py ==1.0.3
    - werkzeug ==3.0.6
    - xdg ==6.0.0
    - yarl ==1.16.0

tests:
  - script:
      - bagels --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/EnhancedJax/Bagels
  summary: 'Powerful expense tracker that lives in your terminal.'
  description: |
    Bagels expense tracker is a TUI application where you can track and analyse your money flow, with convenience oriented features and a complete interface.
    Some notable features include:
    - Accounts, (Sub)Categories, Splits, Transfers, Records
    - Templates for Recurring Transactions
    - Add Templated Record with Number Keys
    - Clear Table Layout with Togglable Splits
    - Transfer to and from Outside Tracked Accounts
    - "Jump Mode" Navigation
    - Less and Less Fields to Enter per Transaction, Powered by Transactions and Input Modes
    - Insights
    - Customizable Keybindings and Defaults, such as First Day of Week
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - claudiushaag
    - EnhancedJax
